on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          version: 12.15
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
